import React, { useState, useEffect } from 'react';
import DataTable from '../components/DataTable';
import FilterBar from '../components/FilterBar';
import { getReports, generateReport, deleteReport } from '../services/adminApi';
import toast from 'react-hot-toast';

const ReportsStatistics = () => {
  const [reports, setReports] = useState([]);
  const [pagination, setPagination] = useState(null);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ page: 1, limit: 10 });
  const [modalOpen, setModalOpen] = useState(false);
  const [newReport, setNewReport] = useState({ title: '', type: 'users', filters: {} });

  const fetchReports = async () => {
    setLoading(true);
    try {
      const res = await getReports(filters);
      setReports(res.data.data.items);
      setPagination(res.data.data.pagination);
    } catch (error) {
      toast.error('Failed to load reports');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, [filters]);

  const handleGenerate = async () => {
    try {
      await generateReport(newReport);
      toast.success('Report generated');
      setModalOpen(false);
      fetchReports();
    } catch (error) {
      toast.error('Generation failed');
    }
  };

  const handleDelete = async (id) => {
    try {
      await deleteReport(id);
      toast.success('Report deleted');
      fetchReports();
    } catch (error) {
      toast.error('Delete failed');
    }
  };

  const columns = [
    { header: 'Title', accessor: 'title' },
    { header: 'Type', accessor: 'type' },
    { header: 'Generated By', render: (r) => r.generatedBy?.username || 'System' },
    { header: 'Date', render: (r) => new Date(r.createdAt).toLocaleDateString() },
    { header: 'Actions', render: (r) => (
      <button onClick={() => handleDelete(r._id)} className="text-red-600 hover:text-red-800 text-sm">Delete</button>
    )}
  ];

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold text-gray-800 dark:text-white">Reports & Statistics</h1>
        <button 
          onClick={() => setModalOpen(true)}
          className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded"
        >
          Generate New Report
        </button>
      </div>

      <DataTable 
        columns={columns} 
        data={reports} 
        pagination={pagination} 
        onPageChange={(p) => setFilters({...filters, page: p})}
        isLoading={loading}
      />

      {modalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-md shadow-xl">
            <h3 className="text-lg font-bold mb-4 text-gray-900 dark:text-white">Generate Report</h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Title</label>
                <input 
                  type="text" 
                  value={newReport.title} 
                  onChange={(e) => setNewReport({...newReport, title: e.target.value})}
                  className="w-full border rounded px-3 py-2 mt-1 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Type</label>
                <select 
                  value={newReport.type}
                  onChange={(e) => setNewReport({...newReport, type: e.target.value})}
                  className="w-full border rounded px-3 py-2 mt-1 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                >
                  <option value="users">Users</option>
                  <option value="spam">Spam Logs</option>
                  <option value="mail">Mail Logs</option>
                  <option value="contacts">Contacts</option>
                  <option value="security">Security Logs</option>
                </select>
              </div>
            </div>
            <div className="flex justify-end space-x-3 mt-6">
              <button onClick={() => setModalOpen(false)} className="px-4 py-2 border rounded text-gray-700 dark:text-gray-300">Cancel</button>
              <button onClick={handleGenerate} className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">Generate</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportsStatistics;
